[package]
name = "petri_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"
comfy-table = "6.1.0"

[dependencies.rand]
version = "0.8.5"
features = [
    "alloc",
    "std_rng"
]

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",
    "fast-rng",
]
