[package]
name = "petri_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.uuid]
features = [
    "v4",
    "fast-rng",
]
